openapi: 3.1.0
x-stoplight:
  id: 291epccbgj72d
info:
  title: vms.v1
  version: '0.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/v1/vms:
    post:
      summary: Create a new VM
      responses:
        '200':
          description: OK
      operationId: post-api-v1-vms
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                memory:
                  type: integer
                vcpu:
                  type: integer
              required:
                - name
                - memory
                - vcpu
            examples:
              example-1:
                value:
                  name: ubuntu20.04
                  memory: 2048
                  vcpu: 4
      tags:
        - vm
    get:
      summary: Get all VMs list
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  vms:
                    type: array
                    items:
                      $ref: '#/components/schemas/vm'
              examples:
                example-1:
                  value:
                    vms:
                      - name: ubuntu20.04
                        metadata:
                          id: v1
                          api_version: 4e0a3c48-f483-422a-b520-2820207cef42
                        memory: 2048
                        vcpu: 4
                        devices:
                          disk:
                            - type: qcow2
                              path: /var/lib/libvirt/images/ubuntu22.04.qcow2
      operationId: get-api-v1-vms
      tags:
        - vm
  '/api/v1/vms/{vmId}':
    parameters:
      - schema:
          type: string
        name: vmId
        in: path
        required: true
    get:
      summary: Get a VM
      tags:
        - vm
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vm'
              examples:
                example-1:
                  value:
                    name: ubuntu20.04
                    metadata:
                      id: v1
                      api_version: 4e0a3c48-f483-422a-b520-2820207cef42
                    memory: 2048
                    vcpu: 4
                    devices:
                      disk:
                        - type: qcow2
                          path: /var/lib/libvirt/images/ubuntu22.04.qcow2
      operationId: get-api-v1-vms-vmId
    patch:
      summary: Update a VM
      operationId: patch-api-v1-vms-vmId
      responses:
        '200':
          description: OK
      tags:
        - vm
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                memory:
                  type: integer
                vcpu:
                  type: integer
            examples:
              example-1:
                value:
                  name: centos_stream
                  memory: 1024
                  vcpu: 2
components:
  schemas:
    vm:
      title: vm
      x-stoplight:
        id: 5txew3qu80ak2
      type: object
      x-tags:
        - vm
      description: ''
      properties:
        name:
          type: string
        metadata:
          type: object
          properties:
            id:
              type: string
            api_version:
              type: string
        memory:
          type: integer
        vcpu:
          type: integer
        devices:
          type: object
          properties:
            disk:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                  path:
                    type: string
tags:
  - name: vm
